### ISSUE TITLE
When cache partitioning was introduced

### ISSUE THREAD

**Issue by hober** [w3ctag/caching-bundling-sustainability#1]
> Double-keyed caching was introduced in 2020

I think you mean [2013](https://bugs.webkit.org/show_bug.cgi?id=110269)? (2020 is when Chrome introduced it.)

**Comment by miketaylr** [comment]
Also note that Chrome shipped a triple-keyed cache in 2020: (top-level site, current-frame site, resource URL) (possibly more, depending on how you count various bits in the cache key depending on context).
