### ISSUE TITLE
Missing text

### ISSUE THREAD

**Issue by hober** [w3ctag/caching-bundling-sustainability#2]
The Abstract commits the document to describing two possible future approaches:

> The finding suggests experimenting with smart delays for cache fetches and bundling with delta transport as potential solutions.

The document needs to follow through on this commitment. This one sentence in §5 Closing Remarks isn't sufficient:

> One idea that would be worth experimenting with is to re-use existing ideas such as introducing smart delays (e.g. within the standard deviance for the distribution) for cache fetches to mitigate user fingerprinting.

**Comment by plinss** [comment]
Further input on the smart delays, the client could store the time taken to download the resource originally and use that as a basis for a synthetic per-origin delay (adding some random variance to prevent correlation). This might yield delays that are more consistent with the user's normal experience (where their bandwidth might differ significantly from the average).
